name: dsen2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.7
  - numpy=1.26.3
  - tensorflow=2.15.0
  - keras=2.15.0
  - scikit-image=0.22.0
  - imageio=2.33.1
  - rasterio=1.3.9
  - pyproj=3.6.1
  - matplotlib=3.8.2
  - pydot=2.0.0
